# -*- coding: utf-8 -*-
"""

QBeach plugin for QGIS: Make Xbeach models in QGIS.
Initially built upon a template generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
First protoype March, 2026
Subalpine Software
GNU GPL V 3
    ____    ____                  __  
   / __ \  / __ )___  ____  _____/ /_ 
  / / / / / __  / _ \/ __ `/ ___/ __ \
 / /_/ / / /_/ /  __/ /_/ / /__/ / / /
 \___\_\/_____/\___/\__,_/\___/_/ /_/ 

 """

def classFactory(iface):
    from .QBeach import QBeach
    return QBeach(iface)
