# -*- coding: utf-8 -*-
"""

QBeach plugin for QGIS: Make Xbeach models in QGIS.
Initially built upon a template generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
First protoype March, 2026
Subalpine Software
GNU GPL V 3
    ____    ____                  __  
   / __ \  / __ )___  ____  _____/ /_ 
  / / / / / __  / _ \/ __ `/ ___/ __ \
 / /_/ / / /_/ /  __/ /_/ / /__/ / / /
 \___\_\/_____/\___/\__,_/\___/_/ /_/ 

 """

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.PyQt.QtGui import QIcon
from qgis.core import QgsProject
from .QBeach_dockwidget import QBeachDockWidget
from .config import DEFAULT_SETTINGS
import os.path

try:
    RIGHT_DOCK_WIDGET_AREA = Qt.DockWidgetArea.RightDockWidgetArea  # Qt6
except AttributeError:
    RIGHT_DOCK_WIDGET_AREA = Qt.RightDockWidgetArea  # Qt5

class QBeach:

    def __init__(self, iface):

        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = u'&QBeach'
        self.toolbar = self.iface.addToolBar(u'QBeach')
        self.toolbar.setObjectName(u'QBeach')
        self.pluginIsActive = False
        self.dockwidget = None

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Create and register a QGIS toolbar button and/or menu entry.

        Args:
            icon_path (str): Path to the icon file on disk.
            text (str): Display text for the action.
            callback (callable): Function to invoke when the action is triggered.
            enabled_flag (bool): Whether the action starts enabled.
            add_to_menu (bool): Whether to add to the QBeach plugin menu.
            add_to_toolbar (bool): Whether to add to the QBeach toolbar.
            status_tip (str, optional): Status bar tip text.
            whats_this (str, optional): What's This help text.
            parent (QWidget, optional): Parent widget for the action.

        Returns:
            QAction: The newly created action.
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Set up the plugin toolbar button and menu entry."""

        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=u'QBeach',
            callback=self.run,
            parent=self.iface.mainWindow())

    def onClosePlugin(self):
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False

    def unload(self):
        """Remove the plugin toolbar button and menu entry."""
        for action in self.actions:
            self.iface.removePluginMenu(
                u'&QBeach',
                action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run(self):
        """Launch the QBeach dock widget.

        Validates the project CRS is UTM, initialises the dock widget
        on first launch, resets grid and parameter states, collapses
        all group boxes, and displays the widget.
        """

        canvas = self.iface.mapCanvas() # require UTM coordinates
        project_crs = QgsProject.instance().crs()
        if "UTM" not in project_crs.description().upper():
            QMessageBox.critical(self.iface.mainWindow(), "Invalid CRS", "QBeach only works in UTM coordinates.")
            return

        if not self.pluginIsActive: # activate plugin and set initial conditions
            
            self.pluginIsActive = True
            if self.dockwidget == None:
                self.dockwidget = QBeachDockWidget(self.iface)
            
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockwidget)
            
            self.dockwidget.resetGrid()
            self.dockwidget.resetInputParams()
            
        self.dockwidget.show()
        
        # collapse all collapsible group boxes and reset tab
        self.dockwidget.gridGroupBox.setCollapsed(True)
        self.dockwidget.bathyGroupBox.setCollapsed(True)
        self.dockwidget.gbOptionalFiles.setCollapsed(True)
        self.dockwidget.depGroupBox.setCollapsed(True)
        self.dockwidget.gbInputParameters.setCollapsed(True)
        self.dockwidget.gbOutputVariables.setCollapsed(True)
        self.dockwidget.gbUseGrdDep.setCollapsed(True)
        self.dockwidget.gbOutputModel.setCollapsed(True)
        self.dockwidget.resultsGroupBox.setCollapsed(True)
        self.dockwidget.tabQBeach.setCurrentIndex(0)
