# -*- coding: utf-8 -*-
"""

QBeach plugin for QGIS: Make Xbeach models in QGIS.
Initially built upon a template generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
First protoype March, 2026
Subalpine Software
GNU GPL V 3
    ____    ____                  __  
   / __ \  / __ )___  ____  _____/ /_ 
  / / / / / __  / _ \/ __ `/ ___/ __ \
 / /_/ / / /_/ /  __/ /_/ / /__/ / / /
 \___\_\/_____/\___/\__,_/\___/_/ /_/ 

 """

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.PyQt.QtGui import QIcon
from qgis.core import QgsProject
from .QBeach_dockwidget import QBeachDockWidget
from .resources import *
from .config import DEFAULT_SETTINGS
import os.path

class QBeach:

    def __init__(self, iface):

        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = u'&QBeach'
        self.toolbar = self.iface.addToolBar(u'QBeach')
        self.toolbar.setObjectName(u'QBeach')
        self.pluginIsActive = False
        self.dockwidget = None

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.toolbar.addAction(action)
        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)
        self.actions.append(action)
        return action

    def initGui(self):

        icon_path = ':/plugins/QBeach/icon.png'
        self.add_action(
            icon_path,
            text=u'QBeach',
            callback=self.run,
            parent=self.iface.mainWindow())

    def onClosePlugin(self):
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(
                u'&QBeach',
                action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run(self):
        
        canvas = self.iface.mapCanvas() # require UTM coordinates
        project_crs = QgsProject.instance().crs()
        if "UTM" not in project_crs.description().upper():
            QMessageBox.critical(self.iface.mainWindow(), "Invalid CRS", "QBeach only works in UTM coordinates.")
            return

        canvas = self.iface.mapCanvas() # initial values for launch/reset
        extentCenter = canvas.extent().center()
        easting = extentCenter.x()
        northing = extentCenter.y()
        initialDistx = DEFAULT_SETTINGS['distx']
        initialDisty = DEFAULT_SETTINGS['disty']
        initialResX = DEFAULT_SETTINGS['resx']
        initialResY = DEFAULT_SETTINGS['resy']
        initialRotation = DEFAULT_SETTINGS['rotation']
        initialDuration = DEFAULT_SETTINGS['duration']
        initialTide = DEFAULT_SETTINGS['tide']
        initialHm0 = DEFAULT_SETTINGS['Hm0']
        initialTp = DEFAULT_SETTINGS['Tp']
        initialMainAng = DEFAULT_SETTINGS['mainAngle']
        initialGammajsp = DEFAULT_SETTINGS['gammajsp']
        initialSpread = DEFAULT_SETTINGS['spread']

        if not self.pluginIsActive: # activate plugin and set initial conditions
            
            self.pluginIsActive = True
            if self.dockwidget == None:
                self.dockwidget = QBeachDockWidget(self.iface)
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            
            self.dockwidget.dsbEasting.setValue(easting)
            self.dockwidget.dsbNorthing.setValue(northing)
            self.dockwidget.dsbXdist.setValue(initialDistx)
            self.dockwidget.dsbYdist.setValue(initialDisty)
            self.dockwidget.dsbXresolution.setValue(initialResX)
            self.dockwidget.dsbYresolution.setValue(initialResY)
            self.dockwidget.dsbRotation.setValue(initialRotation)

            self.dockwidget.sbModelDuration.setValue(initialDuration)
            self.dockwidget.dsbTide.setValue(initialTide)
            self.dockwidget.dsbWaveHeight.setValue(initialHm0)
            self.dockwidget.dsbWavePeriod.setValue(initialTp)
            self.dockwidget.dsbWaveDirection.setValue(initialMainAng)
            self.dockwidget.dsbGammaJSP.setValue(initialGammajsp)
            self.dockwidget.dsbSpreading.setValue(initialSpread)
            
        self.dockwidget.show()
        
        # collapse all collapsible group boxes and reset tab
        self.dockwidget.gridGroupBox.setCollapsed(True)
        self.dockwidget.bathyGroupBox.setCollapsed(True)
        self.dockwidget.depGroupBox.setCollapsed(True)
        self.dockwidget.gbInputParameters.setCollapsed(True)
        self.dockwidget.gbUseGrdDep.setCollapsed(True)
        self.dockwidget.gbOutputModel.setCollapsed(True)
        self.dockwidget.tabQBeach.setCurrentIndex(0)
