# -*- coding: utf-8 -*-
"""

QBeach plugin for QGIS: Make Xbeach models in QGIS.
Initially built upon a template generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
First protoype March, 2026
Subalpine Software
GNU GPL V 3
    ____    ____                  __  
   / __ \  / __ )___  ____  _____/ /_ 
  / / / / / __  / _ \/ __ `/ ___/ __ \
 / /_/ / / /_/ /  __/ /_/ / /__/ / / /
 \___\_\/_____/\___/\__,_/\___/_/ /_/ 

 """

import os
import datetime
import numpy as np
from .config import DEFAULT_SETTINGS

from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import pyqtSignal, QTimer
from qgis.gui import QgsFileWidget
from qgis.core import (QgsRasterLayer, Qgis, 
                       QgsMapLayerProxyModel, QgsProject)

from .core.grid import calculate_grid, GridVisualizer
from .core.raster import sample_raster_at_grid, sample_vector_at_grid, create_temp_raster, apply_viridis_renderer, HAS_GDAL
from .core.export import export_xbeach_model, load_grid_files
from .core.netcdf import get_netcdf_info, read_netcdf_variable
from .core.compat import QGIS_INFO, QGIS_SUCCESS, load_ui_type

FORM_CLASS, _ = load_ui_type(os.path.join(
    os.path.dirname(__file__), "QBeach_dockwidget_base.ui"))

class QBeachDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, iface, parent=None):

        super(QBeachDockWidget, self).__init__(parent)
        self.iface = iface
        self.setupUi(self)

        # enable external links in the info text browsers
        self.txtbModelMaker.setOpenExternalLinks(True)
        self.txtbBathyBuilder.setOpenExternalLinks(True)

        # restrict layer selectors to raster or vector
        self.mlcbBathySource.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.mlcbManningSource.setFilters(QgsMapLayerProxyModel.VectorLayer)
        self.mlcbNonErodibleSource.setFilters(QgsMapLayerProxyModel.VectorLayer)
        self.mlcbSedimentSource.setFilters(QgsMapLayerProxyModel.VectorLayer)

        # restrict file widgets by file types
        self.xgrdQgsFileWidget.setFilter("*.grd")
        self.ygrdQgsFileWidget.setFilter("*.grd")
        self.beddepQgsFileWidget.setFilter("*.dep")
        self.xgrdQgsFileWidget2.setFilter("*.grd")
        self.ygrdQgsFileWidget2.setFilter("*.grd")
        self.beddepQgsFileWidget2.setFilter("*.dep")
        self.qgsfwXgridBB.setFilter("*.grd")
        self.qgsfwYgridBB.setFilter("*.grd")
        self.qgsfwBedDepBB.setFilter("*.dep")
        self.xboutputFileWidget.setFilter("*.nc")

        # restrict directory selectors to directories
        self.fwSetwd.setStorageMode(QgsFileWidget.GetDirectory)
        self.fwSetwd2.setStorageMode(QgsFileWidget.GetDirectory)
        self.fwSetwdBB2.setStorageMode(QgsFileWidget.GetDirectory)

        # connect button clicks
        self.pbCancelBathy.clicked.connect(self.close)
        self.pbCancelModel.clicked.connect(self.close)
        self.pbCancelRW.clicked.connect(self.close)
        self.pbDrawOrigin.clicked.connect(self.drawGrid)
        self.pbResetGrid.clicked.connect(self.resetGrid)
        self.pbResetParams.clicked.connect(self.resetInputParams)
        self.pushButton.clicked.connect(self.exportBathy)
        self.pbExportOptionalFiles.clicked.connect(self.exportOptionalFiles)
        self.pbDrawGrdDep.clicked.connect(self.plotGrdDep)
        self.pbExportModel.clicked.connect(self.exportModel)
        self.pbPlotVariable.clicked.connect(self.onPlotVariable)
        self.xboutputFileWidget.fileChanged.connect(self.onNetcdfFileChanged)
        self.cmboxVariable.currentIndexChanged.connect(self.onVariableChanged)
        self.sliderTimeStep.valueChanged.connect(self.onSliderChanged)
        self.mlcbManningSource.layerChanged.connect(self.onManningLayerChanged)
        self.mlcbNonErodibleSource.layerChanged.connect(self.onNonErodibleLayerChanged)
        self.mlcbSedimentSource.layerChanged.connect(self.onSedimentLayerChanged)
        self.cbManningLayer.toggled.connect(self.onManningLayerToggled)
        self.cbManningDefaultOnly.toggled.connect(self.onManningDefaultOnlyToggled)
        self.cbNonErodibleLayer.toggled.connect(self.onNonErodibleLayerToggled)
        self.cbNeDefaultOnly.toggled.connect(self.onNeDefaultOnlyToggled)
        self.cbSedimentLayer.toggled.connect(self.onSedimentLayerToggled)

        # initialize optional layer enabled states
        self.onManningLayerToggled(self.cbManningLayer.isChecked())
        self.onNonErodibleLayerToggled(self.cbNonErodibleLayer.isChecked())
        self.onSedimentLayerToggled(self.cbSedimentLayer.isChecked())

        # reset optional layer defaults
        self.dsbDefaultManning.setValue(DEFAULT_SETTINGS['manning'])
        self.dsbDefaultNE.setValue(DEFAULT_SETTINGS['erodible_depth'])
        
        self.visualizer = GridVisualizer(iface)
        self.var_map = {}
        
        self.resetGrid()
        self.resetInputParams()

    def closeEvent(self, event):
        self.visualizer.clear()
        self.resetGrid()
        self.resetInputParams()

        # collapse all collapsible group boxes and reset tab
        self.gridGroupBox.setCollapsed(True)
        self.bathyGroupBox.setCollapsed(True)
        self.gbOptionalFiles.setCollapsed(True)
        self.depGroupBox.setCollapsed(True)
        self.gbInputParameters.setCollapsed(True)
        self.gbOutputVariables.setCollapsed(True)
        self.gbUseGrdDep.setCollapsed(True)
        self.gbOutputModel.setCollapsed(True)
        self.resultsGroupBox.setCollapsed(True)
        self.tabQBeach.setCurrentIndex(0)

        # uncheck optional checkboxes
        self.cbManningDefaultOnly.setChecked(False)
        self.cbManningLayer.setChecked(False)
        self.cbNeDefaultOnly.setChecked(False)
        self.cbNonErodibleLayer.setChecked(False)
        self.cbSedimentLayer.setChecked(False)

        # reset optional layer defaults
        self.dsbDefaultManning.setValue(DEFAULT_SETTINGS['manning'])
        self.dsbDefaultNE.setValue(DEFAULT_SETTINGS['erodible_depth'])

        # clear layer combo boxes
        self.mlcbBathySource.setLayer(None)
        self.mlcbManningSource.setLayer(None)
        self.mlcbNonErodibleSource.setLayer(None)
        self.mlcbSedimentSource.setLayer(None)
        self.cbManningHeading.clear()

        # clear file widgets
        self.fwSetwd.setFilePath("")
        self.fwSetwd2.setFilePath("")
        self.xgrdQgsFileWidget.setFilePath("")
        self.ygrdQgsFileWidget.setFilePath("")
        self.beddepQgsFileWidget.setFilePath("")
        self.xgrdQgsFileWidget2.setFilePath("")
        self.ygrdQgsFileWidget2.setFilePath("")
        self.beddepQgsFileWidget2.setFilePath("")
        
        # clear optional file widgets
        self.qgsfwXgridBB.setFilePath("")
        self.qgsfwYgridBB.setFilePath("")
        self.qgsfwBedDepBB.setFilePath("")
        self.fwSetwdBB2.setFilePath("")

        self.closingPlugin.emit()
        event.accept()


################################################################
##################### BATHY BUILDER ############################
################################################################


    def resetGrid(self):
        canvas = self.iface.mapCanvas()
        extentCenter = canvas.extent().center()
        self.dsbEasting.setValue(extentCenter.x())
        self.dsbNorthing.setValue(extentCenter.y())
        self.dsbXdist.setValue(DEFAULT_SETTINGS['distx'])
        self.dsbYdist.setValue(DEFAULT_SETTINGS['disty'])
        self.dsbXresolution.setValue(DEFAULT_SETTINGS['resx'])
        self.dsbYresolution.setValue(DEFAULT_SETTINGS['resy'])
        self.dsbRotation.setValue(DEFAULT_SETTINGS['rotation'])
        self.visualizer.clear()

    def getGridParams(self):
        return {
            'originEasting': self.dsbEasting.value(),
            'originNorthing': self.dsbNorthing.value(),
            'distx': self.dsbXdist.value(),
            'disty': self.dsbYdist.value(),
            'dx': self.dsbXresolution.value(),
            'dy': self.dsbYresolution.value(),
            'angle': self.dsbRotation.value()
        }

    def drawGrid(self):
        p = self.getGridParams()
        worldROI, E_world, N_world = calculate_grid(p)
        self.visualizer.draw(worldROI, E_world, N_world, 
                             DEFAULT_SETTINGS['skip_x'], 
                             DEFAULT_SETTINGS['skip_y'])

    def exportBathy(self):

        bathy_layer = self.mlcbBathySource.currentLayer()
        output_dir = self.fwSetwd.filePath()
        
        if not bathy_layer or not isinstance(bathy_layer, QgsRasterLayer):
            QtWidgets.QMessageBox.warning(self, "Invalid Source", "Please select a valid elevation (depth) raster layer.")
            return
        if not self.visualizer.roi_rubberband:
            QtWidgets.QMessageBox.warning(self, "No Grid", "Please draw a grid before interpolating/exporting.")
            return
        if not output_dir or not os.path.isdir(output_dir):
            QtWidgets.QMessageBox.warning(self, "Invalid Path", "Please select a valid output directory.")
            return

        self.iface.messageBar().pushMessage("QBeach", "Extracting bathymetry...", level=QGIS_INFO, duration=2)

        # get XB grid
        p = self.getGridParams()
        worldROI, E_world, N_world = calculate_grid(p)
        
        # Sample raster at grid nodes
        Z_world = sample_raster_at_grid(bathy_layer, E_world, N_world)

        try:
            np.savetxt(os.path.join(output_dir, "x.grd"), E_world, fmt="%.4f")
            np.savetxt(os.path.join(output_dir, "y.grd"), N_world, fmt="%.4f")
            np.savetxt(os.path.join(output_dir, "bed.dep"), Z_world, fmt="%.4f")
            
            QTimer.singleShot(2500, lambda: QtWidgets.QMessageBox.information(
                self, "Success", f".grd and .dep files saved to {output_dir}"))
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", f"Failed to save files: {str(e)}")

    def exportOptionalFiles(self):
        output_dir = self.fwSetwdBB2.filePath()
        path_x = self.qgsfwXgridBB.filePath()
        path_y = self.qgsfwYgridBB.filePath()
        path_z = self.qgsfwBedDepBB.filePath()

        if not all([path_x, path_y, path_z]) or not all([os.path.isfile(p) for p in [path_x, path_y, path_z]]):
            QtWidgets.QMessageBox.warning(self, "Missing Files", "Please select x.grd, y.grd, and bed.dep files to use as a template.")
            return

        if not output_dir or not os.path.isdir(output_dir):
            QtWidgets.QMessageBox.warning(self, "Invalid Path", "Please select a valid output directory.")
            return

        try:
            E, N, Z = load_grid_files(path_x, path_y, path_z)
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error Loading Files", f"Failed to load template grid/depth files: {str(e)}")
            return

        self.iface.messageBar().pushMessage("QBeach", "Generating optional files...", level=QGIS_INFO, duration=2)

        # Manning
        if self.cbManningLayer.isChecked():
            default_val = self.dsbDefaultManning.value()

            if self.cbManningDefaultOnly.isChecked():
                manning_grid = np.full_like(Z, default_val, dtype=float)
            else:
                layer = self.mlcbManningSource.currentLayer()
                attribute = self.cbManningHeading.currentText()

                if not layer or not attribute:
                    QtWidgets.QMessageBox.warning(self, "Manning Layer Error", "Please select a valid Manning layer and attribute field.")
                    return

                try:
                    manning_grid = sample_vector_at_grid(layer, attribute, default_val, E, N)
                except Exception as e:
                    QtWidgets.QMessageBox.critical(self, "Manning Error", f"Failed to generate manning.dep: {str(e)}")
                    return

            np.savetxt(os.path.join(output_dir, "manning.dep"), manning_grid, fmt="%.4f")

        # Non-Erodible
        if self.cbNonErodibleLayer.isChecked():
            default_val = self.dsbDefaultNE.value()

            if self.cbNeDefaultOnly.isChecked():
                ne_grid = np.full_like(Z, default_val, dtype=float)
            else:
                layer = self.mlcbNonErodibleSource.currentLayer()
                attribute = self.cbNonErodibleHeading.currentText()

                if not layer or not attribute:
                    QtWidgets.QMessageBox.warning(self, "Non-Erodible Error", "Please select a valid non-erodible layer and attribute field.")
                    return

                try:
                    ne_grid = sample_vector_at_grid(layer, attribute, default_val, E, N)
                except Exception as e:
                    QtWidgets.QMessageBox.critical(self, "Non-Erodible Error", f"Failed to generate nonerodible.dep: {str(e)}")
                    return

            np.savetxt(os.path.join(output_dir, "nonerodible.dep"), ne_grid, fmt="%.4f")

            # (Future: handle Sediment)


        #QtWidgets.QMessageBox.information(self, "Success", f"Optional files saved to {output_dir}")
        QTimer.singleShot(2500, lambda: QtWidgets.QMessageBox.information(
                self, "Success", f"Optional files saved to {output_dir}"))

    def onManningLayerChanged(self, layer):
        self.cbManningHeading.clear()
        if layer and layer.isValid():
            fields = [field.name() for field in layer.fields()]
            self.cbManningHeading.addItems(fields)

    def onNonErodibleLayerChanged(self, layer):
        self.cbNonErodibleHeading.clear()
        if layer and layer.isValid():
            fields = [field.name() for field in layer.fields()]
            self.cbNonErodibleHeading.addItems(fields)

    def onSedimentLayerChanged(self, layer):
        self.cbSedimentHeading.clear()
        if layer and layer.isValid():
            fields = [field.name() for field in layer.fields()]
            self.cbSedimentHeading.addItems(fields)

    def onManningLayerToggled(self, checked):
        self._updateManningWidgetState()
        self.updateOptionalExportState()

    def _updateManningWidgetState(self):
        layer_active = self.cbManningLayer.isChecked()
        use_default_only = self.cbManningDefaultOnly.isChecked()
        self.cbManningDefaultOnly.setEnabled(layer_active)
        self.mlcbManningSource.setEnabled(layer_active and not use_default_only)
        self.cbManningHeading.setEnabled(layer_active and not use_default_only)
        self.dsbDefaultManning.setEnabled(layer_active)

    def onManningDefaultOnlyToggled(self, checked):
        self._updateManningWidgetState()

    def onNonErodibleLayerToggled(self, checked):
        self._updateNonErodibleWidgetState()
        self.updateOptionalExportState()

    def _updateNonErodibleWidgetState(self):
        layer_active = self.cbNonErodibleLayer.isChecked()
        use_default_only = self.cbNeDefaultOnly.isChecked()
        self.cbNeDefaultOnly.setEnabled(layer_active)
        self.mlcbNonErodibleSource.setEnabled(layer_active and not use_default_only)
        self.cbNonErodibleHeading.setEnabled(layer_active and not use_default_only)
        self.dsbDefaultNE.setEnabled(layer_active)

    def onNeDefaultOnlyToggled(self, checked):
        self._updateNonErodibleWidgetState()

    def onSedimentLayerToggled(self, checked):
        self.mlcbSedimentSource.setEnabled(checked)
        self.cbSedimentHeading.setEnabled(checked)
        self.dsbDefaultGrainSize.setEnabled(checked)
        self.updateOptionalExportState()

    def updateOptionalExportState(self):
        any_checked = (self.cbManningLayer.isChecked() or 
                       self.cbNonErodibleLayer.isChecked() or 
                       self.cbSedimentLayer.isChecked())
        
        self.qgsfwXgridBB.setEnabled(any_checked)
        self.qgsfwYgridBB.setEnabled(any_checked)
        self.qgsfwBedDepBB.setEnabled(any_checked)
        self.fwSetwdBB2.setEnabled(any_checked)
        self.pbExportOptionalFiles.setEnabled(any_checked)


################################################################
##################### MODEL MAKER ##############################
################################################################


    def resetInputParams(self):
        self.sbModelDuration.setValue(DEFAULT_SETTINGS['duration'])
        self.dsbTide.setValue(DEFAULT_SETTINGS['tide'])
        self.dsbWaveHeight.setValue(DEFAULT_SETTINGS['Hm0'])
        self.dsbWavePeriod.setValue(DEFAULT_SETTINGS['Tp'])
        self.dsbWaveDirection.setValue(DEFAULT_SETTINGS['mainAngle'])
        self.dsbSpreading.setValue(DEFAULT_SETTINGS['spread'])
        self.dsbGammaJSP.setValue(DEFAULT_SETTINGS['gammajsp'])
        
        # reset output variable checkboxes
        self.cbCelerity.setChecked(False)
        self.cbEnergy.setChecked(False)
        self.cbWaveHeight.setChecked(False)
        self.cbSedero.setChecked(False)
        self.cbMeanWaveAngle.setChecked(False)
        self.cbBedLevel.setChecked(False)
        self.cbWaterLevel.setChecked(False)
        
        # reset mean variable checkboxes
        self.cbCelerityMean.setChecked(False)
        self.cbEnergyMean.setChecked(False)
        self.cbWaveHeightMean.setChecked(False)
        self.cbSederoMean.setChecked(False)
        self.cbMeanU.setChecked(False)
        self.cbMeanV.setChecked(False)
        self.cbWaterLevelMean.setChecked(False)
        
        # clear output variable line edits
        self.leOutputVariables.clear()
        self.leOtherMeans.clear()

    def getModelParams(self):

        nx = 0
        ny = 0
        alfa = 0.0
        path_x = self.xgrdQgsFileWidget2.filePath()
        path_y = self.ygrdQgsFileWidget2.filePath()
        path_z = self.beddepQgsFileWidget2.filePath()

        found_grid = False
        if os.path.isfile(path_x) and os.path.isfile(path_y):
            try:
                X = np.loadtxt(path_x)
                Y = np.loadtxt(path_y)
                
                # standard 2D grid case
                if X.ndim == 2 and Y.ndim == 2 and X.shape == Y.shape:
                    rows, cols = X.shape
                    nx = cols - 1
                    ny = rows - 1
                    found_grid = True
                
                # 1D profile case (ny = 0)
                elif X.ndim == 1 and Y.ndim == 1 and X.shape == Y.shape:
                    nx = len(X) - 1
                    ny = 0
                    found_grid = True
                    
            except Exception:
                pass

        if not found_grid:
            for path in [path_x, path_y, path_z]:
                if path and os.path.isfile(path):
                    try:
                        data = np.loadtxt(path)
                        if data.ndim == 2:
                            rows, cols = data.shape
                            nx = cols - 1
                            ny = rows - 1
                            break
                        elif data.ndim == 1:
                            nx = len(data) - 1
                            ny = 0
                            break
                    except Exception:
                        continue

        # limit angles to [0, 360]
        main_angle = self.dsbWaveDirection.value()
        thetamin = (main_angle - 90) % 360
        thetamax = (main_angle + 90) % 360

        # get global variables (checkboxes + line edit)
        var_map = {
            self.cbCelerity: "c",
            self.cbEnergy: "E",
            self.cbWaveHeight: "H",
            self.cbSedero: "sedero",
            self.cbMeanWaveAngle: "thetamean",
            self.cbBedLevel: "zb",
            self.cbWaterLevel: "zs"
        }
        
        selected_vars = [name for cb, name in var_map.items() if cb.isChecked()]
        
        other_vars = self.leOutputVariables.text()
        if other_vars:
            extra_vars = [v.strip() for v in other_vars.split(',') if v.strip()]
            selected_vars.extend(extra_vars)

        selected_vars = sorted(list(set(selected_vars)))

        # get mean variables (checkboxes + line edit)
        mean_var_map = {
            self.cbCelerityMean: "c",
            self.cbEnergyMean: "E",
            self.cbWaveHeightMean: "H",
            self.cbSederoMean: "sedero",
            self.cbMeanU: "u",
            self.cbMeanV: "v",
            self.cbWaterLevelMean: "zs"
        }
        
        selected_means = [name for cb, name in mean_var_map.items() if cb.isChecked()]
        
        other_means = self.leOtherMeans.text()
        if other_means:
            extra_means = [v.strip() for v in other_means.split(',') if v.strip()]
            selected_means.extend(extra_means)
            
        selected_means = sorted(list(set(selected_means)))

        return {
            'date': datetime.datetime.now().strftime("%Y-%m-%d"),
            'duration': self.sbModelDuration.value(),
            'tstop': self.sbModelDuration.value()+1,
            'tintg': int(self.sbModelDuration.value()/10),
            'tide': self.dsbTide.value(),
            'Hm0': self.dsbWaveHeight.value(),
            'Tp': self.dsbWavePeriod.value(),
            'mainAngle': main_angle,
            'thetamin': thetamin,
            'thetamax': thetamax,
            'spread': self.dsbSpreading.value(),
            'gammajsp': self.dsbGammaJSP.value(),
            'alfa': alfa,
            'nx': nx,
            'ny': ny,
            'nglobalvar': len(selected_vars),
            'global_vars': "\n".join(selected_vars),
            'nmeanvar': len(selected_means),
            'mean_vars': "\n".join(selected_means)
        }

    def exportModel(self):

        output_dir = self.fwSetwd2.filePath()
        plugin_dir = os.path.dirname(__file__)
        params_template = os.path.join(plugin_dir, 'ParamsTemplate.txt')
        p2 = self.getModelParams()

        if (p2['nglobalvar'] + p2['nmeanvar']) == 0:
            QtWidgets.QMessageBox.warning(self, "No Output Variables", "Please select at least one output variable (Global or Mean) before exporting.")
            return

        if not all([self.xgrdQgsFileWidget2.filePath(), self.ygrdQgsFileWidget2.filePath(), self.beddepQgsFileWidget2.filePath()]):
            QtWidgets.QMessageBox.warning(self, "Missing Files", "Please select x.grd, y.grd, and bed.dep files.")
            return
            
        if not output_dir or not os.path.isdir(output_dir):
            QtWidgets.QMessageBox.warning(self, "Invalid Directory", "Please select a valid output directory.")
            return
        
        try:
            export_xbeach_model(output_dir, params_template, p2)

            self.iface.messageBar().pushMessage(
                "Working on it:", 
                "Preparing model files.", 
                level=QGIS_SUCCESS, 
                duration=2
            )
            QTimer.singleShot(2500, lambda: QtWidgets.QMessageBox.information(
                self, "Success", f"Model files exported to {output_dir}"))
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", f"Failed to export model: {str(e)}")


################################################################
##################### RESULTS WRANGLER #########################
################################################################


    def plotGrdDep(self):
        
        if not HAS_GDAL:
            QtWidgets.QMessageBox.critical(self, "GDAL Missing", "The GDAL library is required to plot the temporary raster layer.")
            return

        path_x = self.xgrdQgsFileWidget.filePath()
        path_y = self.ygrdQgsFileWidget.filePath()
        path_z = self.beddepQgsFileWidget.filePath()

        if not all([path_x, path_y, path_z]) or not all([os.path.isfile(p) for p in [path_x, path_y, path_z]]):
            QtWidgets.QMessageBox.warning(self, "Missing Files", "Please select all three files (x.grd, y.grd, and bed.dep).")
            return

        try:
            E, N, Z = load_grid_files(path_x, path_y, path_z)
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error Loading Files", f"Failed to load grid/depth files: {str(e)}")
            return

        if not (E.shape == N.shape == Z.shape):
            QtWidgets.QMessageBox.critical(self, "Shape Mismatch", "The selected files must have the same dimensions (rows x columns).")
            return

        self.visualizer.clear()
        
        try:
            
            crs = self.iface.mapCanvas().mapSettings().destinationCrs()
            temp_path = create_temp_raster(E, N, Z, crs.toWkt())
            
            rlayer = QgsRasterLayer(temp_path, "DepFileTemp")
            if not rlayer.isValid():
                QtWidgets.QMessageBox.critical(self, "Load Error", "Failed to load the temporary raster layer.")
                return

            apply_viridis_renderer(rlayer, float(np.nanmin(Z)), float(np.nanmax(Z)))
            QgsProject.instance().addMapLayer(rlayer)
            
            rows, cols = (E.shape[0], E.shape[1]) if E.ndim == 2 else (1, len(E))
            QtWidgets.QMessageBox.information(self, "Success", f"Model grid loaded. Dimensions: nx={cols-1}, ny={rows-1}.")
            
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", f"Failed to create raster: {str(e)}")

    def onNetcdfFileChanged(self, file_path):
        if not file_path or not os.path.isfile(file_path):
            self.cmboxVariable.clear()
            self.var_map = {}
            self.sliderTimeStep.setEnabled(False)
            return
            
        try:
            variables, var_map = get_netcdf_info(file_path)
            self.var_map = var_map
            
            # populate variable dropdown
            self.cmboxVariable.blockSignals(True)
            self.cmboxVariable.clear()
            self.cmboxVariable.addItems(variables)
            self.cmboxVariable.blockSignals(False)
            
            # populate slider values
            self.onVariableChanged()
                
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "NetCDF Error", 
                f"Failed to read NetCDF info: {str(e)}", 
                level=Qgis.MessageLevel.Warning
            )
            self.cmboxVariable.clear()
            self.var_map = {}
            self.sliderTimeStep.setEnabled(False)

    def onVariableChanged(self):
        var_name = self.cmboxVariable.currentText()
        if var_name in self.var_map:
            count = self.var_map[var_name]['count']
            
            self.sliderTimeStep.blockSignals(True)
            self.sliderTimeStep.setMinimum(0)
            
            # disable slider when working with mean values
            if count > 1:
                self.sliderTimeStep.setEnabled(True)
                self.sliderTimeStep.setMaximum(count - 1)
            else:
                self.sliderTimeStep.setEnabled(False)
                self.sliderTimeStep.setMaximum(0)
                
            self.sliderTimeStep.setSingleStep(1)
            self.sliderTimeStep.setValue(0)
            self.sliderTimeStep.blockSignals(False)
            self.onSliderChanged(0)
        else:
            self.sliderTimeStep.setEnabled(False)
            self.sliderTimeStep.setMaximum(0)
            self.sliderTimeStep.setValue(0)
            self.labTimeStep.setText("Time step: N/A")

    def onSliderChanged(self, value):
        var_name = self.cmboxVariable.currentText()
        if var_name in self.var_map:
            count = self.var_map[var_name]['count']
            self.labTimeStep.setText(f"Time step: {value + 1} (of {count})") 
        else:
            self.labTimeStep.setText("Time step:")

    def onPlotVariable(self):
        file_path = self.xboutputFileWidget.filePath()
        var_name = self.cmboxVariable.currentText()
        timestep = self.sliderTimeStep.value()
    
        if not file_path or not os.path.isfile(file_path):
            QtWidgets.QMessageBox.warning(self, "Missing File", "Please select a valid .nc file.")
            return
        if not var_name:
            QtWidgets.QMessageBox.warning(self, "Missing Variable", "Please select a variable to plot.")
            return
            
        self.iface.messageBar().pushMessage("QBeach", f"Plotting {var_name} at step {timestep}...", level=Qgis.MessageLevel.Info, duration=2)
    
        try:
            E, N, Z = read_netcdf_variable(file_path, var_name, timestep)
            
            if E is None or N is None or Z is None:
                QtWidgets.QMessageBox.critical(self, "Error", "Failed to read data or coordinates from NetCDF.")
                return
    
            crs = self.iface.mapCanvas().mapSettings().destinationCrs()
            temp_path = create_temp_raster(E, N, Z, crs.toWkt())
            
            layer_name = f"{var_name}_step{timestep}"
            rlayer = QgsRasterLayer(temp_path, layer_name)
            
            if not rlayer.isValid():
                QtWidgets.QMessageBox.critical(self, "Load Error", "Failed to load the temporary raster layer.")
                return
    
            z_valid = Z[~np.isnan(Z)] # values used to apply styles to raster
            if z_valid.size > 0:
                z_min = float(np.nanmin(z_valid))
                z_max = float(np.nanmax(z_valid))
            else:
                z_min, z_max = 0.0, 1.0
            
            apply_viridis_renderer(rlayer, z_min, z_max)
            QgsProject.instance().addMapLayer(rlayer)
            
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", f"Failed to plot variable: {str(e)}")